DROP SCHEMA IF EXISTS locAutomoveisBEG;

CREATE DATABASE locAutomoveisBEG;

USE locAutomoveisBEG;

SET STORAGE_ENGINE=InnoDB;
SET NAMES 'utf8';

CREATE TABLE IF NOT EXISTS  TB_CLIENTE(
  ID_CLIENTE INT AUTO_INCREMENT NOT NULL,
  NM_CLIENTE VARCHAR(50) NOT NULL,
  CPF_CLIENTE VARCHAR(14) NOT NULL,
  RG_CLIENTE VARCHAR(12) NOT NULL,
  EST_EMISSOR CHAR(2),
  EMAIL_CLIENTE VARCHAR(50) NOT NULL,
  DT_NASC DATE NOT NULL,
  SEXO_CLIENTE VARCHAR(12) NOT NULL,
  REG_CLIENTE VARCHAR(20) NOT NULL,
  CNH_CLIENTE VARCHAR(20) NOT NULL,
  TELEFONE_CLIENTE VARCHAR(13) NOT NULL,
  DT_VALIDADE_CNH DATE NOT NULL,
PRIMARY KEY (ID_CLIENTE)  
);

CREATE TABLE IF NOT EXISTS TB_AUTOMOVEL(
  ID_AUTOMOVEL INT AUTO_INCREMENT NOT NULL,
  GRUPO_AUTOMOVEL VARCHAR(1),
  ACESSORIOS_AUTOMOVEL SMALLINT,
  NUM_CHASSI_AUTOMOVEL VARCHAR(20) NOT NULL, 
  NUM_PLACA_AUTOMOVEL  VARCHAR(7) NOT NULL,
  CIDADE_AUTOMOVEL VARCHAR(25) NOT NULL,
  UF_AUTOMOVEL CHAR(2) NOT NULL,
  KM_AUTOMOVEL DOUBLE NOT NULL,
  MODELO_AUTOMOVEL VARCHAR(25) NOT NULL,
  FABRICANTE_AUTOMOVEL VARCHAR(30) NOT NULL,
  TARIFA_AUTOMOVEL DOUBLE NOT NULL,
  TARIFA_KM_CONTROLADO DOUBLE NOT NULL,
  TP_STATUS INT NOT NULL,
PRIMARY KEY (ID_AUTOMOVEL)
);

CREATE TABLE IF NOT EXISTS TB_LOCACAO(
  ID_LOCACAO INT AUTO_INCREMENT NOT NULL,
  DATA_LOCACAO DATETIME  NOT NULL,
  DATA_DEVOLUCAO_LOCACAO DATETIME NOT NULL,
  AGENCIA_LOCACAO VARCHAR(4) NOT NULL,
  AGENCIA_DEVOLUCAO_LOCACAO VARCHAR(4) NOT NULL,  
  LOCAL_EMPRESTIMO_LOCACAO VARCHAR(20) NOT NULL,
  LOCAL_DEVOLUCAO_LOCACAO VARCHAR(20)  NOT NULL ,
  TIPO_TARIFA_LOCACAO SMALLINT NOT NULL,
  ID_CLIENTE INT,
  ID_AUTOMOVEL INT,
 PRIMARY KEY (ID_LOCACAO),
 FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE) ,
 FOREIGN KEY (ID_AUTOMOVEL) REFERENCES TB_AUTOMOVEL (ID_AUTOMOVEL)
);

CREATE TABLE IF NOT EXISTS TB_DEVOLUCAO(
 ID_DEVOLUCAO INT AUTO_INCREMENT NOT NULL,
 DATA_DEVOLUCAO_LOCACAO DATETIME NOT NULL,
 LOCAL_DEVOLUCAO_LOCACAO VARCHAR(30) NOT NULL ,
 KM_RODADA_ATUAL DOUBLE NOT NULL,
 AGENCIA_DEVOLUCAO VARCHAR(30) NOT NULL,
 ID_LOCACAO INT,
 PRIMARY KEY (ID_DEVOLUCAO),
 FOREIGN KEY (ID_LOCACAO) REFERENCES TB_LOCACAO(ID_LOCACAO)
);

CREATE TABLE IF NOT EXISTS TB_PAGAMENTO(
  ID_PAGAMENTO INT AUTO_INCREMENT NOT NULL,
  DATA_PAGAMENTO DATETIME  NOT NULL,
  VLR_PAGAMENTO DOUBLE NOT NULL,
  ID_CLIENTE INT,
  ID_LOCACAO INT,
 PRIMARY KEY (ID_PAGAMENTO),
 FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE) ,
 FOREIGN KEY (ID_LOCACAO) REFERENCES TB_LOCACAO (ID_LOCACAO)
 );

CREATE TABLE IF NOT EXISTS TB_PAGAMENTO_CREDITO(
  ID_PAGAMENTO_C INT AUTO_INCREMENT NOT NULL,
  OPERADORA_CARTAO VARCHAR(30) NOT NULL,
  NM_CLIENTE VARCHAR(50) NOT NULL,
  CPF_CLIENTE VARCHAR(15) NOT NULL,
  NUM_CARTAO  VARCHAR(16) NOT NULL,
  DT_VALIDADE VARCHAR(7) NOT NULL,
  COD_SEGURANCA INT NOT NULL,
  CREDITO DOUBLE NOT NULL,
 PRIMARY KEY (ID_PAGAMENTO_C)
);

CREATE TABLE IF NOT EXISTS TB_PAGAMENTO_DEBITO(
  ID_PAGAMENTO_D INT AUTO_INCREMENT NOT NULL,
  BANCO VARCHAR(30) NOT NULL,
  NM_CLIENTE VARCHAR(50) NOT NULL,
  CPF_CLIENTE VARCHAR(15) NOT NULL,
  NUM_AGENCIA INT NOT NULL,
  NUM_CONTA_CORRENTE INT NOT NULL,
  TEL_CLIENTE VARCHAR(20) NOT NULL,
  SALDO DOUBLE NOT NULL,
 PRIMARY KEY (ID_PAGAMENTO_D)
);

CREATE TABLE IF NOT EXISTS TB_LOGIN(
  ID_LOGIN INT AUTO_INCREMENT NOT NULL,
  NM_USUARIO VARCHAR(20) NOT NULL,
  NM_LOGIN VARCHAR(20) NOT NULL,
  NM_SENHA VARCHAR(20) NOT NULL,
  TP_USUARIO INT NOT NULL,  
 PRIMARY KEY (ID_LOGIN)
);


/*UTILIZAR MD5 PARA CRIPTOGRAFIA*/

INSERT INTO TB_LOGIN (NM_USUARIO, NM_LOGIN, NM_SENHA, TP_USUARIO) 
	VALUES ('ADMINSTRADOR', 'ADMIN','1234',0);

INSERT INTO `locautomoveisbeg`.`tb_pagamento_credito` 
(`OPERADORA_CARTAO`, `NM_CLIENTE`, `CPF_CLIENTE`, `NUM_CARTAO`, `DT_VALIDADE`, `COD_SEGURANCA`, `CREDITO`) 
VALUES ('VISA', 'BRUNO SANCHES', '42719464864', '1234123412341234', '05/2015', '123', 350.0);

INSERT INTO `locautomoveisbeg`.`tb_pagamento_debito` 
(`BANCO`, `NM_CLIENTE`, `CPF_CLIENTE`, `NUM_AGENCIA`, `NUM_CONTA_CORRENTE`, `TEL_CLIENTE`, `SALDO`) 
VALUES ('BANCO ITAU', 'BRUNO SANCHES', '42719464864', 1234, 123456, '1127838960', 630.4);

INSERT INTO `locautomoveisbeg`.`tb_automovel` (`ID_AUTOMOVEL`, `GRUPO_AUTOMOVEL`, `ACESSORIOS_AUTOMOVEL`, `NUM_CHASSI_AUTOMOVEL`, `NUM_PLACA_AUTOMOVEL`, `CIDADE_AUTOMOVEL`, `UF_AUTOMOVEL`, `KM_AUTOMOVEL`, `MODELO_AUTOMOVEL`, `FABRICANTE_AUTOMOVEL`, `TARIFA_AUTOMOVEL`, `TARIFA_KM_CONTROLADO`, `TP_STATUS`) 
VALUES (1, 'A', 1, '46546', 'AAA123', 'SP', 'SP', 4, 'TESTE', 'TESTE', 4, 4, 0);

INSERT INTO `locautomoveisbeg`.`tb_cliente` (`ID_CLIENTE`, `NM_CLIENTE`, `CPF_CLIENTE`, `RG_CLIENTE`, `EST_EMISSOR`, `EMAIL_CLIENTE`, `DT_NASC`, `SEXO_CLIENTE`, `REG_CLIENTE`, `CNH_CLIENTE`, `TELEFONE_CLIENTE`, `DT_VALIDADE_CNH`) 
VALUES (1, 'erica cristina', '39341932858', '49834745X', 'SP', 'ericamorena14@hotmail.com', '1995-03-07', 'F', '31554', '45455645', '546456456', '2015-07-01');

INSERT INTO `locautomoveisbeg`.`tb_locacao` (`DATA_LOCACAO`, `DATA_DEVOLUCAO_LOCACAO`, `AGENCIA_LOCACAO`, `AGENCIA_DEVOLUCAO_LOCACAO`, `LOCAL_EMPRESTIMO_LOCACAO`, `LOCAL_DEVOLUCAO_LOCACAO`, `TIPO_TARIFA_LOCACAO`, `ID_CLIENTE`, `ID_AUTOMOVEL`) 
VALUES ('2015-07-03', '2015-07-03', '1234', '1234', 'TESTE', 'TESTE', '0', 1, 1);











